Added TDD blogs
ChristoWolf/awesome-testing-blogs pull request #39
Opened 2023-12-01 09:45 UTC by arbMerl

throw the switch and mark vandervoord blog

2023-12-01 09:55 UTC, ChristoWolf commented on README.md
> -- [Meta-level](#meta-level)
Please revert these.

2023-12-01 10:02 UTC, ChristoWolf requested changes

2023-12-01 10:02 UTC, ChristoWolf commented on README.md
> +- [Throw The Switch:](http://www.throwtheswitch.org/) TDD with focus on embedded systems -> [Ceedling](http://www.throwtheswitch.org/ceedling), [CMock](http://www.throwtheswitch.org/cmock), [Unity](h
According to the website, it should be named `ThrowTheSwitch.org`.

2023-12-01 10:02 UTC, ChristoWolf commented on README.md
> -- [Meta-level](#meta-level)
Please revert these.

2023-12-01 10:02 UTC, ChristoWolf commented on README.md
> +- [Throw The Switch:](http://www.throwtheswitch.org/) TDD with focus on embedded systems -> [Ceedling](http://www.throwtheswitch.org/ceedling), [CMock](http://www.throwtheswitch.org/cmock), [Unity](h
Better: 
TDD-centric blog with focus on embedded systems and related technologies, e.g. [Ceedling](http://www.throwtheswitch.org/ceedling), [CMock](http://www.throwtheswitch.org/cmock), [Unity](http://www.throwtheswitch.org/unity).

2023-12-01 10:02 UTC, ChristoWolf commented on README.md
> +- [Mark VanderVoord´s Blog:](http://vandervoord.net/) Blog from throwtheswitch founder with some [unit test how too´s and ceedling stuff](http://vandervoord.net/series).
- [Mark VanderVoord´s Blog:](http://vandervoord.net/) Blog from ThrowTheSwitch.org founder offering [unit testing and Ceedling guides](http://vandervoord.net/series).

2023-12-04 08:09 UTC, arbMerl commented on README.md
> +- [Mark VanderVoord´s Blog:](http://vandervoord.net/) Blog from throwtheswitch founder with some [unit test how too´s and ceedling stuff](http://vandervoord.net/series).
fixed this suggestion

2023-12-04 08:10 UTC, arbMerl commented
fixed all your suggestions in my main

2023-12-04 15:09 UTC, ChristoWolf approved these changes

2023-12-04 15:10 UTC, merged

2023-12-04 15:10 UTC, ChristoWolf commented
LGTM, thanks again @arbMerl!